# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 10000000
    has_acceleration_limits: false
    max_acceleration: 0
  finger_rotate:
    has_velocity_limits: true
    max_velocity: 10000000
    has_acceleration_limits: false
    max_acceleration: 0
  forearm_rotate:
    has_velocity_limits: true
    max_velocity: 10000000
    has_acceleration_limits: false
    max_acceleration: 0
  left_bracket_to_upper_arm:
    has_velocity_limits: true
    max_velocity: 10000000
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_rotate:
    has_velocity_limits: true
    max_velocity: 10000000
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_joint:
    has_velocity_limits: true
    max_velocity: 10000000
    has_acceleration_limits: false
    max_acceleration: 0